sec/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import dashboard.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard.views.MainDashboardView.as_view(), name='home'),
    url(r'^accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('team_member/', include('team_member.urls')),
    path('task/', include('task.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import re_path, path

import task.views

app_name = 'tasks'

urlpatterns = [
    path('add', task.views.AddTaskView.as_view(), name='add'),
    path('list', task.views.ListTaskView.as_view(), name='list'),
    path('edit/<int:pk>', task.views.EditTaskView.as_view(), name='edit'),
    path('delete/<int:pk>', task.views.DeleteTaskView.as_view(), name='delete'),
    re_path('add_task_activity_form/(?P<task_id>[\d]+)(?:/save_activity_(?P<activity_type>[\d]+))?', task.views.TaskActivityView.as_view(), name='task_activity'),
    path('list/<int:pk>', task.views.TaskActivityListView.as_view(), name='list_task_activity'),
]

task/models/task.py
from django.db import models

from ..constants import status


class Task(models.Model):

    title = models.CharField(max_length=200)

    description = models.TextField(blank=True, default='')

    status = models.SmallIntegerField(default=status.NEW_INT, choices=status.STATUS_OPTIONS)

    due_date = models.DateTimeField(null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)

    updated_date = models.DateTimeField(auto_now_add=True)

    deleted_date = models.DateTimeField(blank=True, null=True)

    company = models.ForeignKey(
        to='company.Company',
        on_delete=models.CASCADE,
        related_name='+'
    )

    assigned_to = models.ForeignKey(
        to='team_member.TeamMember',
        on_delete=models.CASCADE,
        related_name='+'
    )

    created_by = models.ForeignKey(
        to='team_member.TeamMember',
        on_delete=models.CASCADE,
        related_name='+'
    )

    updated_by = models.ForeignKey(
        to='team_member.TeamMember',
        on_delete=models.CASCADE,
        related_name='+'
    )

    deleted_by = models.ForeignKey(
        to='team_member.TeamMember',
        on_delete=models.CASCADE,
        related_name='+',
        null=True,
        blank=True
    )

task/models/task_activity.py
from django.db import models

from ..constants import activity


class TaskActivity(models.Model):

    task = models.ForeignKey(
        'task.Task',
        on_delete=models.CASCADE,
        related_name='activities'
    )

    note = models.TextField(blank=True, default='')

    activity_type = models.SmallIntegerField(
        help_text='Type of activity',
        choices=activity.ACTIVITY_OPTION
    )

    user = models.ForeignKey(
        'team_member.TeamMember',
        on_delete=models.CASCADE,
        related_name='activities'
    )

    created_date = models.DateTimeField(blank=True, auto_now_add=True)

    details = models.TextField(default='', blank=True)


# click on a button
# render task activity form on modal
#


# backend
# create View using FormView
# create form class for each activity (comment, attachment, status)

# frontend
# create modal
# render form on modal

task/models/task_activity_status.py
from django.db import models

from task.constants import status


class TaskActivityStatus(models.Model):

    task_activity = models.OneToOneField(
        'task.TaskActivity',
        primary_key=True,
        on_delete=models.CASCADE,
        related_name='task_activity_status'
    )

    status_before = models.SmallIntegerField(
        choices=status.STATUS_OPTIONS,
        db_index=True
    )

    status_after = models.SmallIntegerField(
        choices=status.STATUS_OPTIONS,
        db_index=True
    )

    created_date = models.DateTimeField(blank=True, auto_now_add=True)

task/models/task_attachment.py
from django.db import models

from task.validator import validate_file_extension


class TaskAttachment(models.Model):
    file = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        max_length=255,
        blank=True,
        null=True,
        validators=[validate_file_extension]
    )

    task_activity = models.ForeignKey(
        'task.TaskActivity',
        on_delete=models.CASCADE,
        related_name='attachments'
    )

    created_date = models.DateTimeField(blank=True, auto_now_add=True)

task/forms/add_task_form.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout

from ..models import Task
from utils.forms.layout import FormCard, SubmitButtons


class AddTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = [
            'title',
            'description',
            'status',
            'due_date',
            'assigned_to',
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        fields = ['title', 'description', 'status', 'due_date', 'assigned_to']

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(css_class='col-sm-3 d-xs-none'),
                FormCard('Task details', fields, icon='queue'),
                css_class='row'
            ),
            Div(
                Div(css_class='col-sm-3 d-xs-none'),
                Div(SubmitButtons(), css_class='col-sm-6 col-xs-12'),
                css_class='row'
            )
        )

    def save(self, commit=True):
        # want to autofill company, created_by, updated_by
        # fill these fields with the current user id
        # need to pass request obejct to the form, access user data, self.request.user
        # get the instance, set the value, instance.created_by_id = self.request.user.pk

        instance = super().save(commit=False)
        instance.company_id = self.request.user.team_member.company_id
        instance.created_by_id = self.request.user.pk
        instance.updated_by_id = self.request.user.pk
        return super().save(commit=True)

task/forms/edit_task.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout

from ..models import Task
from utils.forms.layout import FormCard, EditSubmitButtons


class EditTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = [
            'title',
            'description',
            'status',
            'due_date',
            'assigned_to',
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

        fields = ['title', 'description', 'status', 'due_date', 'assigned_to']

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(css_class='col-sm-3 d-xs-none'),
                FormCard('Task details', fields, icon='queue'),
                css_class='row'
            ),
            Div(
                Div(css_class='col-sm-3 d-xs-none'),
                Div(EditSubmitButtons(), css_class='col-sm-6 col-xs-12'),
                css_class='row'
            )
        )

    def save(self, commit=True):
        # want to autofill company, created_by, updated_by
        # fill these fields with the current user id
        # need to pass request obejct to the form, access user data, self.request.user
        # get the instance, set the value, instance.created_by_id = self.request.user.pk

        instance = super().save(commit=False)
        instance.updated_by_id = self.request.user.pk
        return super().save(commit=True)

task/forms/task_activity_forms.py
import json

from django import forms
from django.urls import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Submit

from ..constants import activity, status
from ..models import Task, TaskActivity, TaskAttachment, TaskActivityStatus


class AddTaskActivityForm(forms.Form):
    def __init__(self, task_id, request, **kwargs):
        self.task_id = task_id
        self.request = request
        super().__init__(**kwargs)
        self.helper = FormHelper()
        # add form action
        self.helper.form_action = self.get_action()
        # add form button
        self.helper.add_input(
            Submit('save', 'Save', css_class='btn btn-success')
        )
        self.helper.add_input(
            Button('cancel', 'Cancel', data_dismiss='modal', css_class='btn btn-link')
        )

    def get_action(self):
        return reverse('tasks:task_activity', kwargs={
            'task_id': self.task_id,
            'activity_type': self.activity_type
        })


class AddCommentForm(AddTaskActivityForm):
    activity_type = activity.ADD_COMMENT_INT
    comment = forms.CharField(label='Your comment', widget=forms.Textarea)

    def save(self, *args, **kwargs):
        # get the form data from self.cleaned_data[]
        comment = self.cleaned_data['comment']
        note = f'{self.request.user.team_member} added comment: "{comment}"'

        return TaskActivity.objects.create(
            note=note,
            task_id=self.task_id,
            activity_type=self.activity_type,
            user=self.request.user.team_member,
            details=json.dumps({
                'user': self.request.user.id,
                'type': self.activity_type,
                'comment': comment
            })
        )


class AddAttachmentForm(AddTaskActivityForm):
    activity_type = activity.ADD_ATTACHMENT_INT
    attachment = forms.FileField(
        widget=forms.ClearableFileInput(attrs={
            'accept': 'image/*, .doc, .docx, .pdf, .xlsx, .xls, .zip'
        })
    )

    def save(self, *args, **kwargs):
        file = self.request.FILES['attachment']
        file_name = file.name
        print(file_name)
        note = f'{self.request.user.team_member} uploaded {file_name}'

        activity = TaskActivity.objects.create(
            note=note,
            task_id=self.task_id,
            activity_type=self.activity_type,
            user=self.request.user.team_member,
            details=json.dumps({
                'user': self.request.user.id,
                'type': self.activity_type,
                'file': file_name
            })
        )

        TaskAttachment.objects.create(
            file=file,
            task_activity=activity
        )

        return activity


class ChangeStatusForm(AddTaskActivityForm):
    activity_type = activity.CHANGE_STATUS_INT
    status = forms.ChoiceField(label='Status', choices=status.STATUS_OPTIONS)

    def save(self, *args, **kwargs):
        new_status = int(self.cleaned_data['status'])
        current_task = Task.objects.get(id=self.task_id)
        current_status = current_task.id
        note = f'{self.request.user.team_member} changed the status to {status.STATUS_OPTIONS_DICT[new_status]}.'

        activity = TaskActivity.objects.create(
            note=note,
            task_id=self.task_id,
            activity_type=self.activity_type,
            user=self.request.user.team_member,
            details=json.dumps({
                'user': self.request.user.id,
                'type': self.activity_type,
                'status_before': current_status,
                'status_after': new_status
            })
        )

        current_task.status = new_status
        current_task.save()

        TaskActivityStatus.objects.create(
            task_activity=activity,
            status_before=current_status,
            status_after=new_status,
        )

        return activity

task/views/add_task.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from utils.views.forms import PassRequestToFormView

from ..forms import AddTaskForm
from ..models import Task


class AddTaskView(PassRequestToFormView, CreateView):
    model = Task
    form_class = AddTaskForm
    template_name = 'add_task_form.html'
    success_url = reverse_lazy('tasks:list')
    suffix = 'tasks'

task/views/delete_task.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from ..models import Task


class DeleteTaskView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:list')

task/views/edit_task.py
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from utils.views.forms import PassRequestToFormView

from ..forms import EditTaskForm
from ..models import Task


class EditTaskView(PassRequestToFormView, UpdateView):
    model = Task
    form_class = EditTaskForm
    template_name = 'edit_task.html'
    success_url = reverse_lazy('tasks:list')
    prefix = 'tasks'

task/views/list_task.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import DetailView, FormView
from django_filters.views import FilterView

from django_tables2.views import SingleTableMixin
from django.shortcuts import reverse

from utils.views import RestrictTaskListMixin

from ..constants.activity import (ADD_COMMENT_INT, ADD_ATTACHMENT_INT, CHANGE_STATUS_INT)
from ..filters import TaskFilter
from ..forms import AddAttachmentForm, AddCommentForm, ChangeStatusForm
from ..models import Task
from ..tables import TaskTable


class ListTaskView(SingleTableMixin, RestrictTaskListMixin, FilterView):
    model = Task
    template_name = 'task_list.html'

    # django table
    table_class = TaskTable

    # django filter
    filterset_class = TaskFilter


class TaskActivityListView(DetailView):
    model = Task
    template_name = 'task_activity_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activities'] = self.object.activities.order_by('-created_date')
        return context


class TaskActivityView(SuccessMessageMixin, FormView):
    success_message = 'Activity recorded'
    template_name = 'task_activity.html'
    form_classes = {
        ADD_COMMENT_INT: AddCommentForm,
        ADD_ATTACHMENT_INT: AddAttachmentForm,
        CHANGE_STATUS_INT: ChangeStatusForm,
    }

    def get_success_url(self):
        return reverse('tasks:task_activity', args=(self.kwargs['task_id'],))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # pass kwargs to form class
        kwargs['task_id'] = self.kwargs['task_id']
        kwargs['request'] = self.request
        return kwargs

    def get_form_class(self):
        # select which form to process based on activity_type
        # can access data on url using self.kwargs['']
        return self.form_classes[int(self.kwargs['activity_type'])]

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # call the save method in form
        form.save()
        return super().form_valid(form)

    def get_context_data(self, form=None):
        context = super().get_context_data(form=form)
        context['forms'] = {
            x: C(**self.get_form_kwargs())
            for x, C in (
                ('comment', AddCommentForm),
                ('attachment', AddAttachmentForm),
                ('status', ChangeStatusForm),
            )
        }
        return context

task/templates/add_task_form.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% load render_bundle from webpack_loader %}

{% block main_css %}
{% endblock %}

{% block main_js %}
{{block.super}}
{% render_bundle 'task_add' %}
{% endblock %}

{% block main_content %}
    <div>
        <div class="animated fadeIn">
            <div class="row">
                <div class="col text-left">
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

task/templates/edit_task.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% load render_bundle from webpack_loader %}

{% block main_css %}
{% endblock %}

{% block main_js %}
{{block.super}}
{% render_bundle 'task_add' %}
{% endblock %}

{% block main_content %}
    <div>
        <div class="animated fadeIn">
            <div class="row">
                <div class="col text-left">
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
    {% include 'task/confirm_delete_modal.html' %}
{% endblock %}

task/templates/task_activity.html
{% load crispy_forms_tags %}
{% include 'master_message.html' %}
<div>
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#comment" role="tab" aria-controls="nav-home" aria-selected="true">Add comment</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#attachment" role="tab" aria-controls="nav-profile" aria-selected="false">Upload document</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#status" role="tab" aria-controls="nav-contact" aria-selected="false">Update status</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="comment" role="tabpanel" aria-labelledby="nav-home-tab">
            {% crispy forms.comment %}
        </div>
        <div class="tab-pane fade" id="attachment" role="attachment" aria-labelledby="nav-profile-tab">
            {% crispy forms.attachment %}
        </div>
        <div class="tab-pane fade" id="status" role="update" aria-labelledby="nav-contact-tab">
            {% crispy forms.status %}
        </div>
    </div>
</div>

task/templates/task_activity_list.html
{%if activities %}
<div class="col" style="max-height:100%; overflow:auto">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">notes</th>
                <th scope="col">created_date</th>
            </tr>
        </thead>
        <tbody>
            {% for activity in activities %}
            <tr>
                <td>
                    {{ activity.note }}
                    {% for attachment in activity.attachments.all %}
                        <br>
                        <a href="{{attachment.file.url}}" target="_blank">{{attachment.file}}</a>
                    {% endfor %}
                </td>
                <td>
                    {{ activity.created_date }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

task/templates/task_list.html
{% extends "master.html" %}
{% load django_tables2 %}
{% load render_table from django_tables2 %}

{% load render_bundle from webpack_loader %}

{% block main_css %}
{{block.super}}
{% endblock %}

{% block main_js %}
  {{block.super}}
  {% render_bundle 'task_list' %}
<script>
    window.urls = {
      task_activity_url: '{% url "tasks:task_activity" 0 %}',
      get_task_activity_url: '{% url "tasks:list_task_activity" 0 %}'
    }
</script>
{% endblock main_js %}

{% block main_content %}
<form method="GET" action="{% querystring %}" id="table_form">
  <div class="card">
    <div class="card-header">
      <div class="row align-items-center">
        <div class="col">
          {% include 'lists/search_bar.html' with field=filter.form.title placeholder='Search by task name' %}
        </div>
        <div class="col-2">
            {{ filter.form.status }}
          </div>
        <div class="col-1">
          {%include 'lists/add_button.html' with reverse_url='tasks:add' title='Create a new task' %}
        </div>
      </div>
    </div>
    <div class="card-body">
        {% render_table table %}
    </div>
  </div>
</form>
{% include 'task/task_activity_modal.html' %}
{% endblock %}